apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke-greg
  namespace: quelpoke-greg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quelpoke-greg
  template:
    metadata:
      labels:
        app: quelpoke-greg
    spec:
      containers:
      - name: quelpoke-greg
        image: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-gregoire/quelpoke:latest
        ports:
        - containerPort: 8080

---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: quelpoke-greg-gateway
  namespace: quelpoke-greg
spec:
  parentRefs:
  - kind: Gateway
    name: external-http-gateway
    namespace: infra
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /greg
    backendRefs:
    - name: quelpoke
      port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: quelpoke-greg-service
spec:
  selector:
    app.kubernetes.io/name: quelpoke-greg
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
