apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke-greg
  namespace: quelpoke-greg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quelpoke-greg
  template:
    metadata:
      labels:
        app: quelpoke-greg
    spec:
      containers:
      - name: quelpoke-greg
        image: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-gregoire/quelpoke:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"

---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: quelpoke-greg-gateway
  namespace: quelpoke-greg
spec:
  parentRefs:
  - kind: Gateway
    name: external-http-gateway
    namespace: infra
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /greg
    backendRefs:
    - name: quelpoke-greg-service
      port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: quelpoke-greg-service
  namespace: quelpoke-greg
spec:
  selector:
    app.kubernetes.io/name: quelpoke-greg
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: external-http-gateway
  namespace: infra
  annotations:
    networking.gke.io/certmap: quelpoke-certmap
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https-listener
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
    - name: http-listener
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
        - kind: HTTPRoute
        namespaces:
          from: All

